### ISSUE TITLE
Google Vision Api  Key  

### ISSUE THREAD

**Issue by Gurmeetkaur5949** [lukevanin/OCRAI#1]
Hello I'm getting an issue in this code .
The GoogleVisionApi key is expired, So what can i do .

**Comment by lukevanin** [comment]
A google account is required for API access. The source code has been updated to load the necessary credentials from a .plist file. The readme includes instructions on setting up the necessary API. Note that the app is currently configured to use Google Vision API for OCR, and the MonkeyLearn API for entity extraction, so you will need an key for both platforms. If you want to only use Google, you can disable the MonkeyLearn API, and enable Google NLP instead. Check in DefaultServiceFactory.swift for the relevant code which can be uncommented.

**Comment by Gurmeetkaur5949** [comment]
​Ok sir Thanks for reply.​
